name: ping-schedule
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/1 * * * *"   # تشغيل كل 15 دقيقة (بالوقت UTC)
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: date
